config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  namespace :java_examinator do
    get "", to: "java_examinator#index"

    resource :classes_constructors_and_object_initializing, only: %i[show]
    resource :introduction_to_object_oriented_programming_encapsulation_inheritance_modifiers, only: %i[show]
    resource :introduction_to_object_oriented_programming_polymorphism_object_classes, only: %i[show]
    resource :abstract_classes_and_interfaces, only: %i[show]
    resource :generics, only: %i[show]
    resource :enums, only: %i[show]
    resource :wrapper_classes, only: %i[show]
    resource :strings, only: %i[show]
  end

  resources :cnf_to_dnf, only: %i[index create]
  resources :recurrence_relations, only: %i[index create]
  resources :solving_recurrence_relations, only: %i[index create]
  resource :sets, only: %i[show] do
    resources :difference, only: %i[create]
    resources :union, only: %i[create]
    resources :interception, only: %i[create]
  end

  resource :number_theory, only: %i[show], module: :number_theory do
    resources :modulo, only: %i[create]
    resources :gcd, only: %i[create]
    resources :modulo_inverse, only: %i[create]
    resources :prime_numbers, only: %i[create]
    resources :prime_factorization, only: %i[create]
    scope module: :modular_arithmetic do
      resources :linear_congruence, only: %i[create]
      resources :chinese_remainder_theorem, only: %i[create]
      resources :addition, only: %i[create]
      resources :multiplication, only: %i[create]
      resources :division, only: %i[create]
      resources :exponentiation, only: %i[create]
    end
  end

  resource :hamming_code, only: %i[show], module: :hamming_code do
    resources :encode, only: %i[create]
    resources :decode, only: %i[create]
  end

  resources :calculate_checksum, only: %i[index create]

  resource :graph_theory, only: %i[show], module: :graph_theory do
    resources :number_of_vertices, only: %i[create]
  end

  get 'health-and-fitness', to: 'home#health_and_fitness'
end

app/controllers/sets_controller.rb
class SetsController < ApplicationController
  def show; end
end

app/views/sets/show.html.erb
<p>Sets</p>
<br/>
<br/>

<%= turbo_frame_tag "sets" do %>
  <p>Difference</p>
  <%= form_with url: sets_difference_index_path, method: :post do |form| %>
    { <%= form.text_field :difference_a, value: params[:difference_a], placeholder: "10, 20, 30" %> }
    -
    { <%= form.text_field :difference_b, value: params[:difference_b], placeholder: "20, 40, 50" %> }
    =
    { <%= form.text_field :difference_result, value: @difference_result, readonly: true %> }
    <%= form.submit %>
  <% end %>
  <br/>

  <p>Union</p>
  <%= form_with url: sets_union_index_path, method: :post do |form| %>
    { <%= form.text_field :union_a, value: params[:union_a], placeholder: "10, 20, 30" %> }
    ∪
    { <%= form.text_field :union_b, value: params[:union_b], placeholder: "20, 40, 50" %> }
    =
    { <%= form.text_field :union_result, value: @union_result, readonly: true %> }
    <%= form.submit %>
  <% end %>
  <br/>

  <p>Intersection</p>
  <%= form_with url: sets_interception_index_path, method: :post do |form| %>
    { <%= form.text_field :interception_a, value: params[:interception_a], placeholder: "10, 20, 30" %> }
    ∩
    { <%= form.text_field :interception_b, value: params[:interception_b], placeholder: "20, 40, 50" %> }
    =
    { <%= form.text_field :interception_result, value: @interception_result, readonly: true %> }
    <%= form.submit %>
  <% end %>
<% end %>