config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  namespace :java_examinator do
    get "", to: "java_examinator#index"

    resource :classes_constructors_and_object_initializing, only: %i[show]
    resource :introduction_to_object_oriented_programming_encapsulation_inheritance_modifiers, only: %i[show]
    resource :introduction_to_object_oriented_programming_polymorphism_object_classes, only: %i[show]
    resource :abstract_classes_and_interfaces, only: %i[show]
    resource :generics, only: %i[show]
    resource :enums, only: %i[show]
    resource :wrapper_classes, only: %i[show]
    resource :strings, only: %i[show]
  end

  resources :cnf_to_dnf, only: %i[index create]
  resources :recurrence_relations, only: %i[index create]
  resources :solving_recurrence_relations, only: %i[index create]
  resource :sets, only: %i[show] do
    resources :difference, only: %i[create]
    resources :union, only: %i[create]
    resources :interception, only: %i[create]
  end

  resource :number_theory, only: %i[show], module: :number_theory do
    resources :modulo, only: %i[create]
    resources :gcd, only: %i[create]
    resources :modulo_inverse, only: %i[create]
    resources :prime_numbers, only: %i[create]
    resources :prime_factorization, only: %i[create]
    scope module: :modular_arithmetic do
      resources :linear_congruence, only: %i[create]
      resources :chinese_remainder_theorem, only: %i[create]
      resources :addition, only: %i[create]
      resources :multiplication, only: %i[create]
      resources :division, only: %i[create]
      resources :exponentiation, only: %i[create]
    end
  end

  resource :hamming_code, only: %i[show], module: :hamming_code do
    resources :encode, only: %i[create]
    resources :decode, only: %i[create]
  end

  resources :calculate_checksum, only: %i[index create]

  resource :graph_theory, only: %i[show], module: :graph_theory do
    resources :number_of_vertices, only: %i[create]
  end

  get 'health-and-fitness', to: 'home#health_and_fitness'
end

app/controllers/number_theory/gcd_controller.rb
class NumberTheory::GcdController < ApplicationController
  def create
    @gcd_result = params[:gcd_a].to_i.gcd(params[:gcd_b].to_i)

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end
end

app/controllers/number_theory/modular_arithmetic/addition_controller.rb
class NumberTheory::ModularArithmetic::AdditionController < ApplicationController
  def create
    if params[:addition_mod].to_i == 0
      return respond_to do |format|
        flash[:error] = "mod is 0"
        format.html { render :index, status: :bad_request }
      end
    end

    @mod_add_result = (
      (params[:addition_a].to_i % params[:addition_mod].to_i) +
      (params[:addition_b].to_i % params[:addition_mod].to_i)
    ) % params[:addition_mod].to_i

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end
end

app/controllers/number_theory/modular_arithmetic/exponentiation_controller.rb
class NumberTheory::ModularArithmetic::ExponentiationController < ApplicationController
  def create
    b = eval(params[:b]).to_i
    e = eval(params[:e]).to_i

    if e > 1000
      return respond_to do |format|
        flash[:error] = "e is too large"
        format.html { render :index, status: :bad_request }
      end
    end

    if params[:mod_exp_mod].to_i == 0
      return respond_to do |format|
        flash[:error] = "mod is 0"
        format.html { render :index, status: :bad_request }
      end
    end

    @result = 1
    exp = 0

    while exp < e
      @mod_exp_result = @mod_exp_result * b % params[:mod_exp_mod].to_i
      exp += 1
    end

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end
end

app/controllers/number_theory/modular_arithmetic/linear_congruence_controller.rb
class NumberTheory::ModularArithmetic::LinearCongruenceController < ApplicationController
  include ExtendedGcd
  def create
    a = params[:linear_congruence_a].to_i
    b = params[:linear_congruence_b].to_i
    n = params[:linear_congruence_mod].to_i

    gcd, _ = ExtendedGcd.extended_gcd(a, n)

    if b % gcd != 0
      return respond_to do |format|
        flash[:error] = "DNE"
        format.html { render :index, status: :bad_request }
      end
    end

    a_prime = a / gcd
    b_prime = b / gcd
    n_prime = n / gcd

    gcd, inv_a_prime, _ = ExtendedGcd.extended_gcd(a_prime, n_prime)
    x0 = (inv_a_prime * b_prime) % n_prime
    x0 += n_prime if x0 < 0

    @linear_congruence_result = (0..10).map { |i| x0 + i * n_prime }

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end
end

app/controllers/number_theory/modular_arithmetic/multiplication_controller.rb
class NumberTheory::ModularArithmetic::MultiplicationController < ApplicationController
  def create
    if params[:multiplication_mod].to_i == 0
      return respond_to do |format|
        flash[:error] = "mod is 0"
        format.html { render :index, status: :bad_request }
      end
    end

    @multiplication_result = (
      (params[:multiplication_a].to_i % params[:multiplication_mod].to_i) *
      (params[:multiplication_b].to_i % params[:multiplication_mod].to_i)
    ) % params[:multiplication_mod].to_i

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end
end

app/controllers/number_theory/modulo_controller.rb
class NumberTheory::ModuloController < ApplicationController
  def create
    if params[:modulo_mod].to_i == 0
      return respond_to do |format|
        flash[:error] = "mod is 0"
        format.html { render :index, status: :bad_request }
      end
    end

    @modulo_result = params[:modulo_a].to_i % params[:modulo_mod].to_i

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end
end

app/controllers/number_theory/modulo_inverse_controller.rb
class NumberTheory::ModuloInverseController < ApplicationController
  include ExtendedGcd

  def create
    gcd, x, _ = ExtendedGcd.extended_gcd(params[:modulo_inverse_a].to_i, params[:modulo_inverse_mod].to_i)
    @modulo_inverse_result = if gcd != 1
      "DNE"
    else
      x % params[:modulo_inverse_mod].to_i
    end

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end
end

app/controllers/number_theory/number_theories_controller.rb
class NumberTheory::NumberTheoriesController < ApplicationController
  def show; end
end

app/controllers/number_theory/prime_factorization_controller.rb
class NumberTheory::PrimeFactorizationController < ApplicationController
  def create
    prime_factors(params[:prime_factorization_number].to_i)

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  end

  private

  def prime_factors(n)
    @prime_factors = []

    PrimeNumbersService.calculate(n:).each do |prime|
      while n % prime == 0
        @prime_factors << prime
        n /= prime
      end
    end
  end
end

app/controllers/number_theory/prime_numbers_controller.rb
class NumberTheory::PrimeNumbersController < ApplicationController
  def create
    @prime_numbers = PrimeNumbersService.calculate(
      from: params[:prime_number_from].to_i,
      n: params[:prime_number_to].to_i
    )

    respond_to do |format|
      format.html { render "number_theory/number_theories/show" }
    end
  rescue ArgumentError => e
    respond_to do |format|
      flash[:error] = e.message
      format.html { render "number_theory/number_theories/show", status: :bad_request }
    end
  end
end

app/views/number_theory/number_theories/show.html.erb
<p>Number Theory</p>
<br/>
<br/>

<%= turbo_frame_tag "number_theory" do %>
  <%= render "partials/flash" %>

  <p>Prime number</p>
  <%= form_with url: number_theory_prime_numbers_path, method: :post do |form| %>
    <%= form.label :prime_number_from, 'from' %>
    <%= form.text_field :prime_number_from, value: params[:prime_number_from] || 2 %>

    <%= form.label :prime_number_to, 'to' %>
    <%= form.text_field :prime_number_to, value: params[:prime_number_to] || 100 %>

    <%= form.submit %>
  <% end %>
  <p>Result: <%= @prime_numbers&.join(', ') %></p>
  <br/>

  <p>Prime factorization</p>
  <%= form_with url: number_theory_prime_factorization_index_path, method: :post do |form| %>
    <%= form.text_field :prime_factorization_number, value: params[:prime_factorization_number] %>
    <%= form.submit %>
  <% end %>
  <p>Result: <%= @prime_factors&.join(', ') %></p>
  <br/>

  <p>Modulo</p>
  <%= form_with url: number_theory_modulo_index_path, method: :post do |form| %>
    <%= form.text_field :modulo_a, value: params[:modulo_a] %>
    ( mod <%= form.text_field :modulo_mod, value: params[:modulo_mod] %> )
     = <%= form.text_field :modulo_result, value: @modulo_result, readonly: true %>
    <%= form.submit %>
  <% end %>
  <br/>

  <p>GCD</p>
  <%= form_with url: number_theory_gcd_index_path, method: :post do |form| %>
    gcd(
      <%= form.text_field :gcd_a, value: params[:gcd_a] %>,
      <%= form.text_field :gcd_b, value: params[:gcd_b] %>
    )
     = <%= form.text_field :gcd_result, value: @gcd_result, readonly: true %>
    <%= form.submit %>
  <% end %>
  <br/>

  <p>Modulo inverse</p>
  <%= form_with url: number_theory_modulo_inverse_index_path, method: :post do |form| %>
    <%= form.text_field :modulo_inverse_a, value: params[:modulo_inverse_a] %>
    ( mod <%= form.text_field :modulo_inverse_mod, value: params[:modulo_inverse_mod] %> )
     = <%= form.text_field :modulo_inverse_result, value: @modulo_inverse_result, readonly: true %>
    <%= form.submit %>
  <% end %>
  <br/>

  <p>Linear congruence</p>
  <%= form_with url: number_theory_linear_congruence_index_path, method: :post do |form| %>
    <%= form.text_field :linear_congruence_a, value: params[:linear_congruence_a] %>
    * x ≡ <%= form.text_field :linear_congruence_b, value: params[:linear_congruence_b] %>
    ( mod <%= form.text_field :linear_congruence_mod, value: params[:linear_congruence_mod] %> )
    <%= form.submit %>
  <% end %>
  <p>Result: <%= @linear_congruence_result&.join(', ') %></p>
  <br/>

  <p>Addition</p>
  <%= form_with url: number_theory_addition_index_path, method: :post do |form| %>
    <%= form.text_field :addition_a, value: params[:addition_a] %>
    + <%= form.text_field :addition_b, value: params[:addition_b] %>
    ( mod <%= form.text_field :addition_mod, value: params[:addition_mod] %> )
     = <%= form.text_field :mod_add_result, value: @mod_add_result, readonly: true %>
    <%= form.submit %>
  <% end %>
  <br/>

  <p>Multiplication</p>
  <%= form_with url: number_theory_multiplication_index_path, method: :post do |form| %>
    <%= form.text_field :multiplication_a, value: params[:multiplication_a] %>
    * <%= form.text_field :multiplication_b, value: params[:multiplication_b] %>
    ( mod <%= form.text_field :multiplication_mod, value: params[:multiplication_mod] %> )
     = <%= form.text_field :multiplication_result, value: @multiplication_result, readonly: true %>
    <%= form.submit %>
  <% end %>
  <br/>

  <p>Exponentiation</p>
  <%= form_with url: number_theory_exponentiation_index_path, method: :post do |form| %>
    <%= form.text_field :b, value: params[:b] %>
    **
    <%= form.text_field :e, value: params[:e] %>
    ( mod <%= form.text_field :mod_exp_mod, value: params[:mod_exp_mod] %> )
     = <%= form.text_field :mod_exp_result, value: @mod_exp_result, readonly: true %>
    <%= form.submit %>
  <% end %>
<% end %>