config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"

  namespace :java_examinator do
    get "", to: "java_examinator#index"

    resource :classes_constructors_and_object_initializing, only: %i[show]
    resource :introduction_to_object_oriented_programming_encapsulation_inheritance_modifiers, only: %i[show]
    resource :introduction_to_object_oriented_programming_polymorphism_object_classes, only: %i[show]
    resource :abstract_classes_and_interfaces, only: %i[show]
    resource :generics, only: %i[show]
    resource :enums, only: %i[show]
    resource :wrapper_classes, only: %i[show]
    resource :strings, only: %i[show]
  end

  resources :cnf_to_dnf, only: %i[index create]
  resources :recurrence_relations, only: %i[index create]
  resources :solving_recurrence_relations, only: %i[index create]
  resource :sets, only: %i[show] do
    resources :difference, only: %i[create]
    resources :union, only: %i[create]
    resources :interception, only: %i[create]
  end

  resource :number_theory, only: %i[show], module: :number_theory do
    resources :modulo, only: %i[create]
    resources :gcd, only: %i[create]
    resources :modulo_inverse, only: %i[create]
    resources :prime_numbers, only: %i[create]
    resources :prime_factorization, only: %i[create]
    scope module: :modular_arithmetic do
      resources :linear_congruence, only: %i[create]
      resources :chinese_remainder_theorem, only: %i[create]
      resources :addition, only: %i[create]
      resources :multiplication, only: %i[create]
      resources :division, only: %i[create]
      resources :exponentiation, only: %i[create]
    end
  end

  resource :hamming_code, only: %i[show], module: :hamming_code do
    resources :encode, only: %i[create]
    resources :decode, only: %i[create]
  end

  resources :calculate_checksum, only: %i[index create]

  resource :graph_theory, only: %i[show], module: :graph_theory do
    resources :number_of_vertices, only: %i[create]
  end

  get 'health-and-fitness', to: 'home#health_and_fitness'
end

app/controllers/cnf_to_dnf_controller.rb
class CnfToDnfController < ApplicationController
  def index; end

  def create
    expression = params[:cnf].gsub(/\p{Space}/, ' ').gsub(/\u200B/, '').squish.gsub("~", "!").gsub("-", "!").gsub("+", "||").gsub(")(", ") && (").gsub(") (", ") && (").upcase

    @variables = expression.scan(/[A-Z]+/).uniq
    num_rows = 2 ** @variables.size

    @table = num_rows.times.map do |i|
      values = i.to_s(2).rjust(@variables.size, "0").chars.map { |bit| bit == "1" }
      Hash[@variables.zip(values)].merge("result" => evaluate_expression(expression, Hash[@variables.zip(values)]))
    end.map { |h| h.transform_keys { |k| k.downcase } }

    @dnf_terms = @table.select { |row| row["result"] == true }.map do |row|
      @variables.map(&:downcase).map { |var| row[var] ? var : "~#{var}" }.join
    end.join("+")

    respond_to do |format|
      format.html { render :index }
    end
  rescue SyntaxError
    respond_to do |format|
      flash[:error] = "Invalid expression"
      format.html { render :index, status: :bad_request }
    end
  end

  private

  def evaluate_expression(expression, values)
    values.each do |variable, value|
      expression = expression.gsub(variable, value.to_s)
    end
    eval(expression)
  end
end

app/views/cnf_to_dnf/index.html.erb
<p>CNF to DNF</p>

<%= turbo_frame_tag "cnf_to_dnf" do %>
  <%= render "partials/flash" %>

  <%= form_with url: cnf_to_dnf_index_path, method: :post do |f| %>
    <%= f.text_area :cnf, value: params[:cnf], rows: 10, cols: 50 %>
    <%= f.submit %>
  <% end %>

  <% if @table.present? %>
    <div style="display: flex; flex-direction: row; gap: 30px; margin-top: 30px;">
      <table style="border-collapse: collapse;">
        <tr>
          <% @variables.each do |variable| %>
            <th style="border: 1px solid black; padding: 8px; text-align: center;"><%= variable.downcase %></th>
          <% end %>
          <th style="border: 1px solid black; padding: 8px; text-align: center;">f</th>
        </tr>
        <% @table.each do |row| %>
          <tr>
            <% row.each do |key, value| %>
            <td style="border: 1px solid black; padding: 5px; text-align: left;"><%= value %></td>
          <% end %>
        </tr>
        <% end %>
      </table>

      <p style="word-break: break-word; overflow-wrap: break-word;">DNF: <%= @dnf_terms %></p>
    </div>
  <% end %>
<% end %>